# Use bash explicitly
set-option -g default-shell /bin/bash
set-option -g default-command /bin/bash

# plugin manager
set -g @plugin 'tmux-plugins/tpm'



# set prefix 
set -g prefix C-s

# Change pane size with mouse
set -g mouse on

# Make sure PATH is updated inside tmux
set-option -g update-environment "PATH"

bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Use Alt-arrow keys without prefix key to switch panes 

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Set easier window split keys
bind-key v split-window -h 
bind-key h split-window -v

# Shift arrow to switch windows
bind -n S-Left previous-window 
bind -n S-Right next-window

# Easily reorder windows with CTRL+SHIFT+Arrow 
bind-key -n C-S-Left swap-window -t -1 
bind-key -n C-S-Right swap-window -t +1


# Tmux Customisation

set-option -g status-position top
set -g status-justify centre


# List of plugins

gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold]  #S #[fg=${gray_light},nobold] | "
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 󰍋 ,}"
set -g window-status-format " #I:#W"
set -g message-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${green_soft}"
set -g status-right "/#{b:pane_current_path}"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
